config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  get 'password/resets'
  root 'pages#home'
  resource :dashboard, only: :show
  resource :registration, only: %i[new create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resource :session, only: %i[new create destroy]
  resource :password_reset, only: %i[new create edit update]
  resource :password, only: %i[edit update]

  get 'user/:id', to: 'users#show', as: 'user'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :room
  belongs_to :user
  # after_commit :broadcast_operation

  def transform(transform_service: Operations::TransformationService, content_edit_service: Operations::ContentEditorService)
    Rails.logger.info "Operation transform #{self.to_s}"
    # Получаем операции до последней версии документа
    #       "user_id <> :current_user_id AND version BETWEEN  :operation_version AND :current_version", {
    current_version_operations = self.operations_to_current_version
    # Трансформируем новую операцию относительно всех операций в текущей версии
    Rails.logger.info "transform_service.call"
    transformed_operation = transform_service.call(
       self,
       current_version_operations.to_a
    )
    # Если операция успешно трансформирована, сохраняем и применяем её
    if transformed_operation
      Rails.logger.info "transformed_operation: #{transformed_operation.inspect}"
      transformed_operation.version = self.room.version+1
      if transformed_operation.save!
        content_edit_service.call(self.room, transformed_operation)
        # ActionCable.server.broadcast("operation_channel_#{self.room.id}",{status: "update_text", operation: self})
        return true
      end
    end
    return false
  end

  def operations_to_current_version
    Operation.where(
      "room_id = :current_room AND version > :operation_version", {
        current_room:  self.room_id,
      current_user_id: self.user_id,
        operation_version: self.version.to_s}
      ).order(version: :desc)
  end
end

app/models/room.rb
class Room < ApplicationRecord
  # has_rich_text :content

  has_many :operations

  validates_uniqueness_of :name
  scope :public_rooms, -> {where(is_private: false)}

  # Создание начальной версии документа
  after_create_commit { broadcast_append_to 'rooms' }


end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :sessions, dependent: :destroy
  scope :all_except, -> (user) {where.not(id: user)}
  after_create_commit {broadcast_append_to 'users'}
  MINIMUM_PASSWORD_LENGTH = 4

  has_secure_password

  validates :password, length: { minimum: MINIMUM_PASSWORD_LENGTH }
  validates :email, presence: true, uniqueness: true

  normalizes :email, with: ->(email) { email.strip.downcase }

  generates_token_for :password_reset, expires_in: 1.hour do
    password_salt.last(10)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :require_authentication

  def show
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :restore_authentication
  def home

  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_authentication

  def edit
  end

  def update
    if Current.user.update(password_params)
      redirect_to dashboard_path, notice: "Password updated"
    else
      flash.now[:notice] = Current.user.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def password_params
    params
      .require(:password)
      .permit(:password, :password_confirmation, :password_challenge)
      .with_defaults(password_challenge: "") # This line is important!
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :require_authentication

  def index
    @single_room = Room.take
    @rooms = Room.new
    @rooms= Room.public_rooms
    @users = User.all_except(Current.user)
  end

  def show
    @single_room = Room.find(params[:id])
    render 'show'
  end

  def create
    # @room = Room.create(name: params["room"]["name"])
    @room = Room.create(name: params["name"])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_signed_in, only: %i[new create]
  before_action :require_authentication, only: :destroy

  def new
  end

  def create
    # Этот метод пытается найти пользователя в базе данных, используя адрес электронной почты из параметров
    if user = User.authenticate_by(session_params)
      sign_in user
      redirect_to dashboard_path, notice: "Logged in with #{user.email}"
    else
      flash.now[:notice] = "Invalid email or password"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    sign_out
    redirect_to root_path, notice: "You have been sign out"
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :restore_authentication
  def show
    redirect_to dashboard_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
  # def transform(left, top)
  #   left = Array(left)
  #   top = Array(top)

  #   return [left, top] if left.empty? || top.empty?

  #   if left.length == 1 && top.length == 1
  #     right = transform_operation(left.first, top.first, true)
  #     bottom = transform_operation(top.first, left.first, false)
  #     return [Array(right), Array(bottom)]
  #   end

  #   right = []
  #   bottom = []

  #   left.each do |left_op|
  #     bottom = []

  #     top.each do |top_op|
  #       right_op, bottom_op = transform(left_op, top_op)
  #       left_op = right_op
  #       bottom.concat(bottom_op)
  #     end

  #     right.concat(left_op)
  #     top = bottom
  #   end

  #   [right, bottom]
  # end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_footer.html.erb
<footer class="footer" ></footer>

app/views/layouts/_navbar.html.erb
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">DipplomApp</a>
        <ul >
          <li><%= link_to "Home", root_path %></li>
          <% if Current.user%>
            <% puts Current.user%>
            <li><%= link_to "Dashboard", dashboard_path %></li>
            <li><%= link_to "Rooms", rooms_path%></li> 
            <li><%= link_to "Edit password", edit_password_path %></li>
            <li><%= button_to "Sign out", session_path, method: :delete %></li>
          <%else%>
           <% puts Current.user%>
           <% puts "Current USER is NOT Found"%>
            <li><%= link_to "Sign in", new_session_path %></li>
            <li><%= link_to "Sign up", new_registration_path %></li>
          <%end%>
        </ul>
</nav>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class:'d-flex') do |f| %>
  <%= f.text_field :name, class: 'form-control', autocomplete: 'off' %>
  <%= f.submit data: {disable_with: false} %>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiplomApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
 
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.8/dist/trix.css">
    <script type="text/javascript" src="https://unpkg.com/trix@2.0.8/dist/trix.umd.min.js"></script>
</head>

  </head>

  <body>
    <header>
      <%= render "layouts/navbar"%>
    </header>
    <main>
      <%= notice %>
      <%= yield %>
    </main>
    <%= render "layouts/footer"%>
  </body>
</html>

app/views/pages/home.html.erb
<div id="page">
  <h1>
    Landing page
  </h1>
  <p>
    This page is public and can be accessed by both authenticated and unauthenticated users.
  </p>
</div>